#!/usr/bin/env bash
# WSL-specific Linux setup — runs AFTER the standard linux.sh module.
# Handles things that differ between native Linux and WSL.
set -e
source core/utils.sh

echo "== WSL-specific setup =="

# ── Enable systemd if not already (WSL 2.0+ supports it) ──
WSL_CONF="/etc/wsl.conf"
if [ -f /proc/version ] && grep -qi microsoft /proc/version 2>/dev/null; then
  if ! grep -q 'systemd=true' "$WSL_CONF" 2>/dev/null; then
    echo "Enabling systemd in WSL..."
    sudo mkdir -p "$(dirname "$WSL_CONF")"
    {
      echo ""
      echo "[boot]"
      echo "systemd=true"
    } | sudo tee -a "$WSL_CONF" >/dev/null
    echo "systemd enabled — takes effect after: wsl --shutdown && wsl"
  else
    echo "systemd already enabled"
  fi
fi

# ── VS Code — use Windows install via 'code' path interop ──
# snap doesn't work in WSL; the Windows VS Code with Remote-WSL extension
# is the correct approach. The 'code' command is available via PATH interop
# when VS Code is installed on the Windows side.
if command_exists code; then
  echo "VS Code accessible via Windows interop"
else
  echo "NOTE: Install VS Code on Windows and enable PATH interop."
  echo "      The Remote-WSL extension makes it work seamlessly inside WSL."
fi

# ── Docker — prefer Docker Desktop integration over native engine ──
# If Docker Desktop is installed on Windows with WSL integration enabled,
# the 'docker' command is already available. Don't install native engine
# on top of it — they conflict.
if command_exists docker; then
  echo "Docker already available (likely via Docker Desktop WSL integration)"
else
  echo "Docker not found. Options:"
  echo "  1. Enable Docker Desktop WSL integration (recommended)"
  echo "  2. Install native Docker Engine (modules/docker/linux.sh)"
fi

# ── DNS — warn if resolv.conf looks auto-generated ──
if [ -f /etc/resolv.conf ] && head -1 /etc/resolv.conf | grep -qi 'generated'; then
  if ! grep -q 'generateResolvConf.*false' "$WSL_CONF" 2>/dev/null; then
    echo "NOTE: /etc/resolv.conf is auto-generated by WSL."
    echo "      If you have DNS issues, add to $WSL_CONF:"
    echo "        [network]"
    echo "        generateResolvConf = false"
  fi
fi

# ── Clean Windows PATH leak ──
# Windows paths leak into WSL $PATH by default, which can cause
# conflicts (e.g., Windows python.exe shadowing Linux python).
# This adds the interop config if not already present.
if ! grep -q 'appendWindowsPath' "$WSL_CONF" 2>/dev/null; then
  echo "NOTE: Windows PATH is appended to WSL PATH by default."
  echo "      To disable, add to $WSL_CONF:"
  echo "        [interop]"
  echo "        appendWindowsPath = false"
fi

echo "== WSL-specific setup complete =="
